-- Copyright 2025 Snowflake Inc.
-- SPDX-License-Identifier: Apache-2.0
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
-- http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.

-- =====================================================
-- Festival Operations Cortex Search Service Information
-- NOTE: Cortex Search service is created AUTOMATICALLY by OpenFlow
-- Google Drive (Cortex connect) connector - no manual creation needed!
-- =====================================================

-- =====================================================
-- VERIFICATION QUERIES
-- Check auto-created Cortex Search services
-- =====================================================

-- List all Cortex Search services (including auto-created ones)
SHOW CORTEX SEARCH SERVICES;

-- Get details of a specific service (replace with actual service name from above)
-- Service names are auto-generated by OpenFlow
DESCRIBE CORTEX SEARCH SERVICE <AUTO_GENERATED_SERVICE_NAME>;

-- =====================================================
-- SAMPLE VALIDATION QUERIES
-- Test the auto-created service after OpenFlow processing
-- =====================================================

-- Example query structure (replace service name with actual auto-generated name)
SELECT PARSE_JSON(
  SNOWFLAKE.CORTEX.SEARCH_PREVIEW(
      '<AUTO_GENERATED_SERVICE_NAME>',
      '{
        "query": "festival operations customer service",
        "columns": [
            "text",
            "channel", 
            "username",
            "workspace_id"
        ],
        "limit": 3
      }'
  )
)['results'] as search_test_results;

-- =====================================================
-- BUSINESS INTELLIGENCE SAMPLE QUERIES
-- Ready-to-use queries for demo purposes
-- =====================================================

-- Strategic Planning Intelligence
SELECT PARSE_JSON(
  SNOWFLAKE.CORTEX.SEARCH_PREVIEW(
      '<AUTO_GENERATED_SERVICE_NAME>',
      '{
        "query": "2025 expansion plans target markets revenue growth",
        "columns": ["text", "channel", "username"],
        "limit": 5
      }'
  )
)['results'] as strategic_insights;

-- Operations Excellence Intelligence  
SELECT PARSE_JSON(
  SNOWFLAKE.CORTEX.SEARCH_PREVIEW(
      '<AUTO_GENERATED_SERVICE_NAME>',
      '{
        "query": "technology modernization projects budgets sound system upgrade",
        "columns": ["text", "channel", "username"],
        "limit": 5
      }'
  )
)['results'] as operations_insights;

-- Compliance & Risk Intelligence
SELECT PARSE_JSON(
  SNOWFLAKE.CORTEX.SEARCH_PREVIEW(
      '<AUTO_GENERATED_SERVICE_NAME>',
      '{
        "query": "health safety policies medical procedures regulatory compliance",
        "columns": ["text", "channel", "username"],
        "limit": 5
      }'
  )
)['results'] as compliance_insights;

-- Knowledge Management Intelligence
SELECT PARSE_JSON(
  SNOWFLAKE.CORTEX.SEARCH_PREVIEW(
      '<AUTO_GENERATED_SERVICE_NAME>',
      '{
        "query": "training materials staff development customer service excellence",
        "columns": ["text", "channel", "username"],
        "limit": 5
      }'
  )
)['results'] as training_insights;

-- =====================================================
-- IMPORTANT NOTES
-- =====================================================

/*
🤖 AUTOMATIC CORTEX SEARCH CREATION:
   - Service is created automatically by OpenFlow Google Drive (Cortex connect) connector
   - No manual CREATE CORTEX SEARCH SERVICE commands needed
   - Service name is auto-generated by OpenFlow
   - Arctic embeddings (snowflake-arctic-embed-m-v1.5) configured automatically
   - Document indexing happens automatically during OpenFlow processing

📊 DEMO WORKFLOW:
   1. Set up OpenFlow Google Drive (Cortex connect) connector
   2. Point connector to "Festival Operations" shared drive
   3. Start connector - it automatically:
      - Processes all documents (PDF, DOCX, PPTX, JPG)
      - Creates Cortex Search service
      - Indexes content with metadata
   4. Use SHOW CORTEX SEARCH SERVICES to find auto-generated service name
   5. Run natural language queries using the service name

🔍 BUSINESS VALUE:
   - Executives can ask questions like "What are our 2025 expansion plans?"
   - Operations teams can query "Find technology modernization projects"
   - Compliance teams can search "Show health and safety policies"
   - All without writing SQL - natural language intelligence!
*/
